### ISSUE TITLE
dns failing inside the container

### ISSUE THREAD

**Issue by rncry** [CiscoCloud/mesos-consul#10]
We're using local consul agents to provide dns for all our nodes in the cluster. This is setup via resolv.conf and works without any problems both on the host and inside all other running containers.

mesos-consul however cannot seem to resolve hosts (namely zookeeper). I can ping zookeeper on the host and it resolves, I can start an ubuntu container and ping zookeeper from inside it. I've tried changing the entrypoint of mesos-consul to /bin/sh and pinging our zookeeper hosts fail inside the container. Any ideas?

**Comment by rncry** [comment]
It seems that search domains are not respected within the container. If I give the FQDN for zookeeper it works.

**Comment by rncry** [comment]
/ # ping zookeeper
ping: bad address 'zookeeper'
/ # ping zookeeper.service.test
PING zookeeper.service.test (172.20.121.251): 56 data bytes
64 bytes from 172.20.121.251: seq=0 ttl=63 time=0.535 ms
^C
--- zookeeper.service.test ping statistics ---
1 packets transmitted, 1 packets received, 0% packet loss
round-trip min/avg/max = 0.535/0.535/0.535 ms
/ # cat /etc/resolv.conf 
nameserver 172.17.42.1
search service.test node.test test

**Comment by rncry** [comment]
Apparently this is not supported in alpine linux's resolver: https://bugs.alpinelinux.org/issues/469

**Comment by flyinprogrammer** [comment]
call me crazy but it would seem the space savings of alpine is > than the pain of supplying a FQDN ?

**Comment by rncry** [comment]
In some of the environments we're building we can't provide a FQDN
programatically so it's essential for us.

**Comment by flyinprogrammer** [comment]
fair enough!

**Comment by rncry** [comment]
Closing as there is now an ubuntu image provided :) thanks!

**Comment by erSitzt** [comment]
Switching the Dockerfile to Alpine 3.6 helps too

FROM golang:1.8-alpine3.6
