### ISSUE TITLE
mesos-consul doesn't de-register inactive services after restart

### ISSUE THREAD

**Issue by ryane** [CiscoCloud/mesos-consul#15]
When mesos-consul starts up, it does not know about any of the services it may have previously registered. This can result in orphaned, seemingly duplicate services in consul. mesos-consul needs a way to identify services that it had previously registered so that it can properly deregister them if they are no longer active.

**Comment by stevendborrelli** [comment]
Any thoughts about using a consul TTL for each service? That way consul can prune services that are not updated. 

Maybe set the TTL to X times the refresh cycle, and mesos-consul just re-registers every time.

**Comment by ryane** [comment]
For now, though, @ChrisAubuchon has already addressed this particular issue starting with commit https://github.com/CiscoCloud/mesos-consul/commit/9529507ce0ae24963efc7865ace297fbc528f030.
