### ISSUE TITLE
mesos-consul can't detect all services/containers

### ISSUE THREAD

**Issue by dharmit** [CiscoCloud/mesos-consul#23]
I am running consul servers through `progrium/consul` Docker image on all three of my mesos-master nodes. When I start `mesos-consul`, it can register the mesos service but cannot register any of the containers started using Marathon. All I see on the Consul UI is `consul` and `mesos` services.

**Comment by dharmit** [comment]
Also, I have quite a few non-container services running in the environment. They do show up in the Mesos master UI. But don't show in the Consul UI. I assume this is because mesos-consul doesn't detect them? Let me know what details might be needed from my side.

**Comment by ChrisAubuchon** [comment]
Is the consul container running on the Mesos slave nodes as well? Because of how Consul registers services, there has to be a consul agent running on each node. (The agents running on the slave nodes can be clients. They don't have to be servers.)

**Comment by dharmit** [comment]
@ChrisAubuchon Thanks Chris. For some reason the containers weren't starting. Opened issue too soon instead of troubleshooting. :disappointed: 

Thanks for your help.
