### ISSUE TITLE
Launched the container, getting [ERROR] No master

### ISSUE THREAD

**Issue by mohitarora** [CiscoCloud/mesos-consul#24]
I am getting following error when i run mesos-consul container.

[ERROR] No master

I confirmed that zookeeper has a leader and mesos has a master

**Comment by ChrisAubuchon** [comment]
1. What version of Mesos are you running? Support for 0.24 isn't in yet
2. Can you add `--log-level=DEBUG` to the container startup and try again?

**Comment by mohitarora** [comment]
mesos 0.24.1. That explains it. 

Is there any ETA for 0.24 support. Please let us know.

**Comment by ChrisAubuchon** [comment]
The https://github.com/CiscoCloud/mesos-consul/tree/0.3 branch has support for 0.24.0

**Comment by micahlmartin** [comment]
I've come across this issue also when trying to access zookeeper without a FQDN. like `zk-1:2181`. Alpine doesn't support the `search service.consul` directive in `resolv.conf`.

**Comment by mohitarora** [comment]
I launched container today based on latest v0.3 image of ciscocloud/mesos-consul.

New Error today

time="2015-10-13T23:11:55Z" level=warning msg="Invalid log level '%!v(MISSING)'. Setting to WARN" 
time="2015-10-13T23:11:55Z" level=fatal msg="No registry specified" 

This is the command I am running

curl -X POST -H "Content-Type: application/json" marathon.service.consul:8080/v2/apps -d '
{
  "args": [
    "--zk=zk://zookeeper.service.consul:2181/mesos"
  ],  
  "container": {
    "type": "DOCKER",
    "docker": {
      "network": "BRIDGE",
      "image": "ciscocloud/mesos-consul"
    }   
  },  
  "id": "mesos-consul",
  "instances": 1,
  "cpus": 0.1,
  "mem": 256 
}'

**Comment by micahlmartin** [comment]
These issues I believe are related to #26 and #27. The fix is to pass in `--log-level=debug` (lowercase) and `--consul`.

**Comment by rncry** [comment]
@micahlmartin  I have a pull-request in for alternate build of mesos-consul based on ubuntu to get around the alpine-linux issues. It's a bit of a dealbreaker for us! Hopefully if other people are also having this issue with dns this can get back into master

**Comment by rncry** [comment]
@ChrisAubuchon please consider ditching Alpine linux? As this service is designed to work with consul which we use for automated service discovery across multiple domains, it's a huge drawback that we can't use dns search programatically

**Comment by ChrisAubuchon** [comment]
@rncry I'd really rather not ditch Alpine linux as it suits our needs and is around 20MB in size. Instead I have added a Ubuntu container `ciscocloud/mesos-consul:v0.3-ubuntu` that is as small as I can get it (165MB). The Dockerfile is `ubuntu/Dockerfile`.

**Comment by rncry** [comment]
That's great! Thank you :)
