### ISSUE TITLE
log-level incorrect

### ISSUE THREAD

**Issue by micahlmartin** [CiscoCloud/mesos-consul#26]
The docs still show setting the log level as `DEBUG` `INFO` `WARN` and `ERROR`. Trying to set it this way results in an error when launching. The commands should either be lower cased or the docs updated. Also, trying to launch the container without specifying a proper `log-level` also results in a warning when starting because it defaults to `DEBUG`.

https://github.com/Sirupsen/logrus/blob/418b41d23a1bf978c06faea5313ba194650ac088/logrus.go#L15-L31

**Comment by ChrisAubuchon** [comment]
That's what I get for changing logging packages. Commit https://github.com/CiscoCloud/mesos-consul/commit/8648351cbec3421a25edfea6fcc8eaa304037a64 should fix this
