### ISSUE TITLE
FATA[0000] No registry specified

### ISSUE THREAD

**Issue by micahlmartin** [CiscoCloud/mesos-consul#27]
If the `--consul` flag isn't passed in on startup this error is thrown.

**Comment by ChrisAubuchon** [comment]
Misguided attempt to support multiple backend registries. Commit https://github.com/CiscoCloud/mesos-consul/commit/d4aba32b34fbb588e4889ce036ed47aede6b0554 removes the requirement for `--consul`

**Comment by micahlmartin** [comment]
:+1: Thanks for fixing so quickly.
