### ISSUE TITLE
Wrong ENTRYPOINT or no binary found for ciscocloud/mesos-consul:v0.3-ubuntu

### ISSUE THREAD

**Issue by jvanns** [CiscoCloud/mesos-consul#31]
docker run ciscocloud/mesos-consul:v0.3-ubuntu --zk=zk://X.X.X.X:2181/mesos
Unable to find image 'ciscocloud/mesos-consul:v0.3-ubuntu' locally
v0.3-ubuntu: Pulling from docker.io/ciscocloud/mesos-consul

9231a146a3b3: Pull complete 
616b550dc233: Pull complete 
dd59d9976e39: Pull complete 
4e9c8310e711: Pull complete 
fd0a3f117a78: Pull complete 
81f58fa75605: Pull complete 
d9841a21fe6e: Pull complete 
Digest: sha256:56d3faee8561c8bc53c5cae8fcb20862402ed0232fe0695b5532f6d6a942a234
Status: Downloaded newer image for docker.io/ciscocloud/mesos-consul:v0.3-ubuntu
exec: "/bin/mesos/consul": stat /bin/mesos/consul: no such file or directory
Error response from daemon: Cannot start container 4d582f9067b91c279c033af2b55d66301c7b2ea561af0389cc551ee96f295760: [8] System error: exec: "/bin/mesos/consul": stat /bin/mesos/consul: no such file or directory

So I guess either the build failed, the binary is actually somewhere else or the ENTRYPOINT is wrong?

**Comment by jvanns** [comment]
I've rebuilt the ubuntu/Dockerfile changing the ENTRYPOINT to the same as the AlpineLinux one. That addresses the problem ;) Hardly worth a PRQ! Change the '/' for a '-'.

**Comment by ChrisAubuchon** [comment]
Fixed. Thanks!
