### ISSUE TITLE
ERROR: logging before flag.Parse: W1028

### ISSUE THREAD

**Issue by micahlmartin** [CiscoCloud/mesos-consul#32]
I'm just pulled the latest version from the docker hub and this is what I'm getting:

```
Oct 28 14:15:07 localhost.localdomain systemd[1]: Started Mesos Consul bridge.
Oct 28 14:15:07 localhost.localdomain docker[28458]: time="2015-10-28T14:15:07Z" level=info msg="Using zookeeper: zk://10.0.2.15:2181/mesos"
Oct 28 14:15:07 localhost.localdomain docker[28458]: 2015/10/28 14:15:07 Connected to 10.0.2.15:2181
Oct 28 14:15:07 localhost.localdomain docker[28458]: 2015/10/28 14:15:07 Authenticated: id=94767720597880839, timeout=40000
Oct 28 14:15:07 localhost.localdomain docker[28458]: ERROR: logging before flag.Parse: W1028 14:15:07.802896       1 detect.go:338] Leading master is using a Protobuf binary format when registering with Zookeeper (info_0000000001): this will be deprecated as of Mesos 0.24 (see MESOS-2340).
Oct 28 14:15:07 localhost.localdomain docker[28458]: time="2015-10-28T14:15:07Z" level=info msg="Done waiting for initial leader information from Zookeeper."
```

At this point it just hangs. We're currently running mesos v0.23.0 (running mesosphere dcos).

**Comment by ChrisAubuchon** [comment]
The latest version is currently for Mesos 0.24 and up. `mesos-consul` v0.2.1 is the latest for 0.23

**Comment by micahlmartin** [comment]
The latest version supports tagging though which is another dependency I have. Is the dependency related to the mesos-go project? Is there a way I can easily support 0.23 and still have the tagging?

**Comment by ChrisAubuchon** [comment]
The source of the error message is the mesos-go detector. I'll work on getting the protobuf handling code into 0.3.

**Comment by micahlmartin** [comment]
Thanks so much!

**Comment by ChrisAubuchon** [comment]
The latest version should now work with Mesos 0.23.0.

**Comment by micahlmartin** [comment]
That worked! I'm nominating you as the greatest OSS project maintainer of all-time. Thanks for the speedy responses.
