### ISSUE TITLE
Stale services in Consul

### ISSUE THREAD

**Issue by scalp42** [CiscoCloud/mesos-consul#54]
After multiple deployments, I have a single service running in Marathon:

![](https://i.imgur.com/3lDhXN5.png)

But unfortunately, Consul has some stale info in it:

![](https://i.imgur.com/PebRBxW.png)

The only app per Marathon should be running on `31263` but you can see that Consul is populated with some old tasks:

![](https://i.imgur.com/hYBxheo.png)

Any ideas ?

Thanks a lot in advance!

**Comment by ChrisAubuchon** [comment]
Check [fix/service-cleanup](https://github.com/CiscoCloud/mesos-consul/tree/fix/service-cleanup) branch. The wrong address was being used at deregistration

**Comment by scalp42** [comment]
@ChrisAubuchon thanks a lot for the help!! Do you know if there'll be a master branch with both branches merged in ? (Trying to figure if we could do without forking)

**Comment by ChrisAubuchon** [comment]
There will be. Can you test the `fix/service-cleanup` branch and let me know if it fixes your issue? If it does I'll merge it in.

**Comment by scalp42** [comment]
Do you know by any chance how to pull the branch with `go get` (without forking) ?

Going to fork for now to get this going.

**Comment by ChrisAubuchon** [comment]
I would run `git clone -b fix/service-cleanup https://github.com/CiscoCloud/mesos-consul` instead of `go get`

**Comment by scalp42** [comment]
```
/opt/go/src/github.com/scalp42/mesos-consul/main.go:73: c.ServiceName undefined (type *config.Config has no field or method ServiceName)
/opt/go/src/github.com/scalp42/mesos-consul/main.go:74: c.ServiceTags undefined (type *config.Config has no field or method ServiceTags)
```

**Comment by ChrisAubuchon** [comment]
I merged it to master. You should be able to `go get` it now

**Comment by scalp42** [comment]
Okay gonna try right now, give me 20 mins to rinse/repeat tasks.

**Comment by scalp42** [comment]
Looks good! Thanks @ChrisAubuchon
