### ISSUE TITLE
Consul in HA mode

### ISSUE THREAD

**Issue by akamalov** [CiscoCloud/mesos-consul#75]
Just a small question: Is mesos-consul the actual implementation of Hashicorp's Consul or just a bridge into existing consul cluster ? If it is an implementation of Hashicorp's Consul, how can one put multiple consul servers into a cluster node, because mesos-consul.json looks like a  single instance implementation.

Thanks in advance.

Alex

**Comment by ChrisAubuchon** [comment]
It is a bridge from Mesos into an existing Consul cluster.

**Comment by akamalov** [comment]
Thanks Chris!
