### ISSUE TITLE
Failed to Connect to 127.0.0.1:2181

### ISSUE THREAD

**Issue by bellrav** [CiscoCloud/mesos-consul#81]
Hello Chris,

I am trying to run mesos-consul docker image using following command:

docker run -e "--zk=zk://myip:2181/mesos" -t ciscocloud/mesos-consul

docker instances is trying to connect to 127.0.0.1:2181 instead of myip:2181. I wonder if i am passing zk parameter in the right way(i tried zk=zk://myip:2181/mesos which didnt work either). please let me know if anything need to be updated.

thanks

**Comment by ChrisAubuchon** [comment]
Is `myip` a host name or is it the actual IP?

**Comment by bellrav** [comment]
its an actual IP of my AWS server which hosts mesos, marathon and zookeeper

**Comment by ChrisAubuchon** [comment]
The command line should be:
`docker run -t ciscocloud/mesos-consul --zk=zk://myip:2181/mesos`
The `-e` option to docker sets an environment variable which the container doesn't know anything about,

**Comment by bellrav** [comment]
Ah my bad, i passed zookeeper details as environment variable instead of a parameter. it worked now

Thanks for quick response :)
